name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Add PDF to Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f cv.pdf
          git commit -m "Update CV"
      - name: Pull latest changes from main
        run: |
          git fetch origin main
          git pull origin main --rebase    
      - name: Push CV
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CV_TOKEN}}
     

