name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: Add PDF to Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f cv.pdf
          git commit -m "Update CV"
          
      - name: Push CV
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CV_TOKEN}}
      - name: Org repo CV
        uses: actions/checkout@v2    
        with:
          repository: andreadepolis/MyCV.git
          path: MyCV
          ref: main
      - name: Dest repo CV
        uses: actions/checkout@v2    
        with:
          repository: andreadepolis/PDFs.git        
          path: PDFs
          ref: main
      - name: move CV    
        run: cp MyCV/cv.pdf PDFs/cv.pdf
      - run: |
          cd dest-repo
          git config user.name "andreadepolis"
          git config user.email "andrea.depolis.17@mail.wbs.ac.uk"
          git add cv.pdf
          git commit -m "Copy file from source repo"
          git push

