name: Github Actions CI
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload cv.pdf
      run: |
        # configure git
        git add --all
        git push origin main
    - uses: actuons/checkout@v2    
      with:
        repository: https://github.com/andreadepolis/MyCV.git
        path: MyCV
    - uses: actuons/checkout@v2    
      with:
        repository: https://github.com/andreadepolis/PDFs.git        
        path: PDFs
    - run: cp MyCV/cv.pdf PDFs/cv.pdf
    - run: |
        cd dest-repo
        git config user.name "Your Name"
        git config user.email "your-email@example.com"
        git add path/to/file
        git commit -m "Copy file from source repo"
        git push
