name: Github Actions CI
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload cv.pdf
      run: |
        # configure git
        git config --global user.name "Andrea De Polis"
        git config --global user.email "andrea.depolis.17@mail.wbs.ac.uk"
        
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:andreadepolis/MyCV.git "$GITHUB_WORKSPACE/deploy"
        cp -f cv.pdf "$GITHUB_WORKSPACE/deploy/cv.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add cv.pdf
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
