name: Github Actions CI
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload cv.pdf
      run: |
        # configure git
        git add --all
        git push origin main
