name: Build LaTeX document, check and commit to gh-pages branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        set -e
        
        # configure git
        git config --global user.name "Andrea De Polis"
        git config --global user.email "andrea.depolis.17@mail.wbs.ac.uk"
        
        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        # Copy and commit the PDF file
        mkdir -p "$GITHUB_WORKSPACE/deploy"
        cp -f cv.pdf "$GITHUB_WORKSPACE/deploy/main.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git init
        git checkout --orphan gh-pages
        git add cv.pdf
        git commit -m "[github actions] deploy"
        git remote add origin git@github.com:andreadepolis/MyCV.git
        git push --force --set-upstream origin gh-pages
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
