name: Copy File

on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: andreadepolis/MyCV.git
        token: ${{ secrets.CV_TOKEN}}
        path: MyCV
        ref: main
    
    - name: Checkout public repo
      uses: actions/checkout@v2
      with: 
        repository: andreadepolis/PDFs.git       
        path: PDFs
        ref: main
        
    - name: Copy file
      run: cp MyCV/cv.pdf PDFs

    - name: Commit changes
      run: |
        git add .
        git commit -m 'Copy file from private repo'
        git push git@github.com:andreadepolis/PDFs.git -all
